version: "3"
services:
  batfish:
    image: "batfish/batfish"
    ports:
      - "9996:9996"
      - "9997:9997"
  netomox-exp:
    image: ghcr.io/ool-mddo/netmox-exp:develop
    environment:
      - BATFISH_HOST=batfish
      - BATFISH_WRAPPER_HOST=batfish-wrapper:5000
    volumes:
      - ../../:/netomox-exp/configs
      - ../mddo_network:/netomox-exp/models
      - ../netoviz_model:/netomox-exp/netoviz_model
    depends_on:
      - batfish
  batfish-wrapper:
    image: ghcr.io/ool-mddo/batfish-wrapper:main
    environment:
      - BATFISH_HOST=batfish
    ports:
      - "5000:5000"
    volumes:
      - ../../:/batfish-wrapper/configs
      - ../mddo_network:/batfish-wrapper/models
    depends_on:
      - batfish
