version: "3.7"
services:
  batfish:
    image: batfish/allinone:latest
    container_name: batfish
    volumes:
    - ./mnt:/mnt
    - ../mddo_network:/mnt/mddo_network
    extra_hosts:
    - "host.docker.internal:host-gateway"
