version: "3.7"
services:
  batfish:
    image: ghcr.io/ool-mddo/mddo-batfish:main 
    volumes:
    - ./mnt:/mnt
    - ../mddo_network:/mnt/mddo_network
    extra_hosts:
    - "host.docker.internal:host-gateway"
