name: config-push

on:
  schedule:
    - cron: '00 */3 * * *'

jobs:
  config-push:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run ansible-playbook to get configs
        run: |
          cd ~mddo/builder
          ansible-runner run . -p playbooks/get_config_runner.yml --container-option="--net=my-multihost-network"
          cp ~mddo/builder/project/configs/* /tmp/configs/mddo_network/configs/
          ansible-runner run . -p playbooks/get_status_runner.yml --container-option="--net=my-multihost-network"
          cp -r ~mddo/builder/project/status/ /tmp/configs/mddo_network/

      - name: Apply config changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply config changes
          repository: /tmp/configs/
          branch: main
          commit_user_name: GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>

