name: config-push

on:
	schdule:
		- cron: '00 */3 * * *'

jobs:
  config-push:
    runs-on: self-hosted

    steps:
      - name: Run ansible-playbook to get configs
        run: |
          cd ~kawaguchi/builder
          ansible-runner run . -p playbooks/get_config_runner.yml --container-option="--net=my-multihost-network"
          cp ~kawaguchi/builder/project/configs/* /tmp/configs/configs/
          ansible-runner run . -p playbooks/get_status_runner.yml --container-option="--net=my-multihost-network"
          cp ~kawaguchi/builder/project/status/* /tmp/configs/status/

      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Apply config changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply config changes
          repository: /tmp/configs/
          branch: main
          commit_user_name: GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>
