name: config-push

on:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  config-push:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Apply config changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply config changes
          branch: main
          commit_user_name: GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
