name: config-push

on:
  schedule:
    - cron: '00 */3 * * *'

jobs:
  config-push:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run ansible-playbook to get configs
        run: |
          cd ~mddo/builder
          ansible-runner run . -p playbooks/get_config_runner.yml --container-option="--net=my-multihost-network"
          cp ./project/configs/* /tmp/configs/mddo_network/configs/
          ansible-runner run . -p playbooks/get_status_runner.yml --container-option="--net=my-multihost-network"
          cp -r ./project/status/ /tmp/configs/mddo_network/

      - name: Commit config changes
        run: |
          cd /tmp/configs
          git add .
          git commit -m "Applu config changes"
          git push origin main

