on:
  push:
    paths:
    - "inet-henge/**"

defaults:
  run:
    working-directory: ./netomox

jobs:
  generate-topo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: prepare playground 
      run: git clone -b feature/gha https://github.com/ool-mddo/playground.git

    - name: delete file
      run: rm -f ~/playground/pushed-flug/*

    - name: make file
      run: touch ~/playground/pushed-flug/202202demo

    - name: write date
      run: echo `date` > ~/playground/pushed-flug/202202demo

    - name: commit files
      run: |
          cd ~/playground
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update from pushed-config"
          git push
