on:
  push:
    branches:
    - feature/extract-L1-topo
jobs:
  extract-L1-topo:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: prepare NetBox
      run: |
        git clone -b release https://github.com/netbox-community/netbox-docker.git
        cd netbox-docker
        tee docker-compose.override.yml <<EOF
        version: '3.4'
        services:
          netbox:
            ports:
            - 8000:8080
        EOF
        docker-compose up -d
      working-directory: ./L1_topo
        
    - name: prepare batfish
      run: docker-compose up -d
      working-directory: ./L1_topo
